# Generated by Django 2.1 on 2019-05-02 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0003_auto_20190502_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='save',
            field=models.ManyToManyField(related_name='save_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
