# Generated by Django 2.1 on 2019-05-02 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0004_photo_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='save',
        ),
        migrations.AddField(
            model_name='photo',
            name='saved',
            field=models.ManyToManyField(related_name='saved_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
